eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eureka-client
  cloud:
    config:
      label: master
      profile: local
      discovery:
        enabled: true
        serviceId: config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#      uri: http://localhost:8888/
server:
  port: 8881


management:
  security:
    enabled: false